# Build the manager binary
FROM golang:alpine3.16 as builder

ARG TARGETOS
ARG TARGETARCH

RUN apk add --no-cache gcc g++ bash curl tar

# Install Delve for debugging
RUN if [ "${TARGETARCH}" = "amd64" ]; then go install github.com/go-delve/delve/cmd/dlv@latest; fi

WORKDIR /devspace

# Install Helm 3
RUN curl -s https://get.helm.sh/helm-v3.1.2-linux-amd64.tar.gz > helm3.tar.gz \
 && tar -zxvf helm3.tar.gz linux-amd64/helm \
 && chmod +x linux-amd64/helm \
 && mv linux-amd64/helm $PWD/helm \
 && rm helm3.tar.gz \
 && rm -R linux-amd64

# Copy the Go Modules manifests
COPY go.mod .
COPY go.sum .
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY main.go .
COPY api/ api/
COPY controllers/ controllers/
COPY pkg/ pkg/

# Build
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -a -o manager main.go

# ENTRYPOINT ["/manager"]
