apiVersion: apps/v1
kind: Deployment
metadata:
  name: capvc-controller-manager
  labels:
    control-plane: capvc-controller-manager
spec:
  selector:
    matchLabels:
      control-plane: capvc-controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: capvc-controller-manager
    spec:
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        image: docker.io/loftsh/cluster-api-provider-vcluster
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
            ephemeral-storage: 1Gi
          requests:
            cpu: 10m
            memory: 64Mi
            ephemeral-storage: 64Mi
      terminationGracePeriodSeconds: 10
